development:
  adapter: mysql2
  encoding: utf8
  database: hereiam_dev
  pool: 5
  username: root
  password:

production:
  adapter: mysql2
  encoding: utf8
  database: hereiam_prod
  pool: 5
  username: root
  password:
